apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttn-gw-register-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttn-gw-register
  template:
    metadata:
      labels:
        app: ttn-gw-register
    spec:
      containers:
      - name: ttn-gw-register
        image: ghcr.io/aschiffler/ttn-gw-register:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "125m"
        envFrom:
        - secretRef:
            name: ttn-gw-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ttn-gw-register-service
spec:
  clusterIP: None
  selector:
    app: ttn-gw-register
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ttn-gw-register-ingress
  annotations:
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - your-domain.com
    secretName: your-domain.com-tls
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /ttn-gw-register
        pathType: Prefix
        backend:
          service:
            name: ttn-gw-register-service
            port:
              number: 8080
---
